cmd_/mnt/workspace/FoodGiver/branchButton/SemesterProjekt3/buttonDriver/button-overlay.dtb := mkdir -p /mnt/workspace/FoodGiver/branchButton/SemesterProjekt3/buttonDriver/ ; gcc -E -Wp,-MD,/mnt/workspace/FoodGiver/branchButton/SemesterProjekt3/buttonDriver/.button-overlay.dtb.d.pre.tmp -nostdinc -I./scripts/dtc/include-prefixes -undef -D__DTS__ -x assembler-with-cpp -o /mnt/workspace/FoodGiver/branchButton/SemesterProjekt3/buttonDriver/.button-overlay.dtb.dts.tmp /mnt/workspace/FoodGiver/branchButton/SemesterProjekt3/buttonDriver/button-overlay.dts ; ./scripts/dtc/dtc -O dtb -o /mnt/workspace/FoodGiver/branchButton/SemesterProjekt3/buttonDriver/button-overlay.dtb -b 0 -i/mnt/workspace/FoodGiver/branchButton/SemesterProjekt3/buttonDriver/ -i./scripts/dtc/include-prefixes -Wno-unit_address_vs_reg -Wno-unit_address_format -Wno-gpios_property -Wno-avoid_unnecessary_addr_size -Wno-alias_paths -Wno-graph_child_address -Wno-simple_bus_reg -Wno-unique_unit_address -Wno-pci_device_reg  -d /mnt/workspace/FoodGiver/branchButton/SemesterProjekt3/buttonDriver/.button-overlay.dtb.d.dtc.tmp /mnt/workspace/FoodGiver/branchButton/SemesterProjekt3/buttonDriver/.button-overlay.dtb.dts.tmp ; cat /mnt/workspace/FoodGiver/branchButton/SemesterProjekt3/buttonDriver/.button-overlay.dtb.d.pre.tmp /mnt/workspace/FoodGiver/branchButton/SemesterProjekt3/buttonDriver/.button-overlay.dtb.d.dtc.tmp > /mnt/workspace/FoodGiver/branchButton/SemesterProjekt3/buttonDriver/.button-overlay.dtb.d

source_/mnt/workspace/FoodGiver/branchButton/SemesterProjekt3/buttonDriver/button-overlay.dtb := /mnt/workspace/FoodGiver/branchButton/SemesterProjekt3/buttonDriver/button-overlay.dts

deps_/mnt/workspace/FoodGiver/branchButton/SemesterProjekt3/buttonDriver/button-overlay.dtb := \

/mnt/workspace/FoodGiver/branchButton/SemesterProjekt3/buttonDriver/button-overlay.dtb: $(deps_/mnt/workspace/FoodGiver/branchButton/SemesterProjekt3/buttonDriver/button-overlay.dtb)

$(deps_/mnt/workspace/FoodGiver/branchButton/SemesterProjekt3/buttonDriver/button-overlay.dtb):
